# Generated by Django 4.2.7 on 2023-11-17 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_work_link_alter_work_slug_alter_work_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workimage',
            name='image',
            field=models.ImageField(upload_to='works/images/'),
        ),
        migrations.AlterField(
            model_name='workimage',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workimages', to='work.work'),
        ),
    ]
