# Generated by Django 4.2.7 on 2024-01-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_alter_workimage_image_alter_workimage_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='work',
            name='show_in_home',
            field=models.BooleanField(default=False),
        ),
    ]
