# Generated by Django 4.2.7 on 2023-11-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0006_alter_networks_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networks',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='networks',
            name='github',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='networks',
            name='instagram',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='networks',
            name='linkedin',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='networks',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='networks',
            name='whatsapp',
            field=models.CharField(max_length=255),
        ),
    ]
